### PR TITLE
Fix deprecation warnings

### PR DESCRIPTION
**Pull request by MortenGregersen**

### CODE REVIEW

**Comment by MortenGregersen** [comment]
There seems to be a problem with the travis file, @evermeer

**Comment by evermeer** [comment]
Awesome! I will also have a look at this PR later today.

**Comment by evermeer** [comment]
I'm struggling to push this version to cocoapods. I keep getting the following error:

```
 -> EVCloudKitDao (3.5.1)
    - ERROR | xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - ERROR | xcodebuild:  EVReflection/Source/EVReflection.swift:1585:81: error: 'range(at:)' has been renamed to 'rangeAt(_:)'
    - NOTE  | xcodebuild:  Foundation.NSTextCheckingResult:28:15: note: 'range(at:)' was introduced in Swift 4
```

Which is strange because swift version is set to 4 and I am using the range(at:)
I will continue with this later today.

**Comment by evermeer** [comment]
I'm still struggling trying to publish this version. I keep on getting the error
`'range(at:)' has been renamed to 'rangeAt(_:)'`
which is actually not true. Its the other way around.
Since it's only used once I will try to avoid using that function.
I will try to fix this later this week.

**Comment by evermeer** [comment]
🎉  YAY
🚀  EVCloudKitDao (3.5.1) successfully published

Sorry I did not base it on this PR... I had some publishing issues and I ended up publishing the changes from master.

**Pull request closed without merging**
