### PR TITLE
Added data state change notifications, ConnectStatus enum

### PR DESCRIPTION
**Pull request by tbaggett**
Added NSNotificationManager-based push notifications to be used in addition to or instead of handlers passed to the connect method. Also changed the completion handler’s isFinished Bool parameter to a new “status” ConnectStatus enumeration value.

Apologies for the extraneous whitespace changes. Also, while I tested the additions in my own tvOS app, I didn't add any testing to the AppMessages sample app. I can do so, perhaps in the TestsViewController if that's what you're using to test with, but wanted input from you before proceeding with that.

Please let me know if you have any questions or concerns.

### CODE REVIEW

**Comment by tbaggett** [comment]
Hmm, maybe the new ConnectStatus enum should be named CompletionStatus? That may be more self-descriptive. I hate I didn't think of that before committing. If you agree that CompletionStatus is a better name for it, I can make the change and commit it before you merge my changes if you like.

**Comment by evermeer** [comment]
You are right :) CompletionStatus sounds better.

**Comment by tbaggett** [comment]
Haha, no problem, I will commit that change in a bit.

**Comment by evermeer** [comment]
It's merged, I will play around with it and add some demo code for it to the AppMessage demo
I also added empty comments for the parameters of the new function. I will fill it in later.

**Comment by tbaggett** [comment]
Okay great, thanks! And sorry I forgot to document the helper method. The NSNotification.userInfo property is an array of AnyObject instances, which makes value types like enums a minor pain to pass through the notification.

**Comment by tbaggett** [comment]
Hey @evermeer, sorry if I'm missing something (other than what I'm actually missing, heh), but I ran pod update on my project to grab the new 2.13.0 version, and all the recent changes have disappeared. I then tried deleting the EVCloudKitDao and EVReflection folders from my project's Pods folder and ran "pods update" again. It replaced the deleted files, but the resulting files were still missing the changes that both you and I have made in the past few days.

I see this output, indicating the new version is being installed:

Installing EVCloudKitDao 2.13.0 (was 2.12.0)
Installing EVReflection 2.11.3 (was 2.11.2)

Any idea on what I'm doing wrong? I haven't had any problem with this previously when updating.

**Comment by evermeer** [comment]
a sorry.. forgot the 'pod trunk push' 
will do that now...

**Comment by tbaggett** [comment]
Oh okay, no problem, in fact I'm kind of relieved. I thought I was losing my mind, haha. Just when I think I know what I'm doing...

Thanks.

**Comment by evermeer** [comment]
It's now pushed to cocoapods as version 2.14.0

**Comment by tbaggett** [comment]
Great, thank you.

**Pull request merged**
