### PR TITLE
Merge remote-tracking branch 'evermeer/master'

### PR DESCRIPTION
**Pull request by tbaggett**
Added an “isFinished” Bool parameter to query completion handlers. The bool is true if all of the query results have been retrieved. It is false if there are more results to be retrieved.

### CODE REVIEW

**Comment by evermeer** [comment]
Strange... according to the status above nothing has changed in this pull request. Am I missing something?

**Comment by tbaggett** [comment]
Doh! Once again, my newb-ness is shining through. Sorry about that.

**Comment by evermeer** [comment]
Done!
Thanks for the PR

**Comment by tbaggett** [comment]
Great! You're welcome, thanks for the library in the first place. It is really helpful.

**Pull request merged**
