### PR TITLE
Update EVCloudKitDao.podspec

### PR DESCRIPTION
**Pull request by tbaggett**
Added tvos 9.0 target, hoping that is all it takes to support use on tvOS.

### CODE REVIEW

**Comment by evermeer** [comment]
I just disabled the tvOS support again. The cocoapod would not validate with it. I guess I first have to add a tvOS target to the solution to see what's wrong.

**Comment by tbaggett** [comment]
No problem, thanks for jumping right on it! I've also downloaded your
source to give it a try on my end.

**Comment by tbaggett** [comment]
After trying to build the code locally, I see that the
CKContainer.discoverAllContactUserInfosWithCompletionHandler method was
removed in tvOS 9.

See
https://developer.apple.com/library/prerelease/tvos/releasenotes/General/tvOS90APIDiffs/Swift/CloudKit.html
for details.

**Comment by evermeer** [comment]
Yes, I noticed. I now have that function with conditional compilation in version 2.9.3
I also had to enable tvOS in my EVReflection library
tvOS is now enabled in both EVReflection and EVCloudKitDao.

**Comment by tbaggett** [comment]
Awesome, you rock man. Thanks so much for the quick attention to that. I will pull the modified source out of my tvOS project and bring in your pods.

**Pull request merged**
